### ISSUE TITLE
Custom ports?

### ISSUE THREAD

**Issue by killerbees19** [srvrco/checkssl#11]
Based on my last [feature request](https://github.com/srvrco/getssl/issues/158) for _getssl_: I'd really appreciate that! :-)

```
# Syntax example…
hostname:https:5001
```

**Comment by srvrco** [comment]
It's supported now ;)   ( or should be - let me know if it's not working ) 

If you have the list in a file just put
hostname:5001

if on the command line then 

> checkssl hostname:5001

**Comment by killerbees19** [comment]
Oh dear, It's just not my day. I should open my eyes…

Untested, but it looks like `REMOTE_EXTRA` is unset in this case.

**Comment by srvrco** [comment]
Yes, "REMOTE_EXTRA" is unset - but it should be for standard https

**Comment by killerbees19** [comment]
You should set it here:

```
PS=443
PORT=443
REMOTE_EXTRA=""
```

Reference: https://github.com/srvrco/checkssl/issues/8#issuecomment-256131454

**Comment by killerbees19** [comment]
> or should be - let me know if it's not working

And indeed, it's not working. ;-)

Because you're checking `PS` and `PORT` is still `443`. There is not default `case` implemented.

**Comment by srvrco** [comment]
Interesting, as it worked for me in my tests.   I've added a line of code that should clarify it though.

**Comment by killerbees19** [comment]
Looks good! :-)

Just a small hint: `REMOTE_EXTRA=""` in line 50 is an unnecessary duplicate now.

**Comment by srvrco** [comment]
Good point.   I've removed that line, and also modified it to allow you to specify  REMOTE_EXTRA in file list
