### ISSUE TITLE
Param --command improve doc.

### ISSUE THREAD

**Issue by ZeusF1** [srvrco/checkssl#12]
@srvrco 

Documentation tweak

I run for example, which is ok
./checkssl -l /etc/letsencrypt/live/ -e 60 -r
domain1.com
domain2.com

Then I would like to renew them
checkssl -l /etc/letsencrypt/live/ -e 60 -r -c '/path/renew_ssl.py -r -u '

tryed also:
checkssl -l /etc/letsencrypt/live/ -e 60 -r -c 'mail mail@domain.com'
but also no luck

How -c works in general?
How I can input $domain in -c ?

Or I should use some bash script to read files with $domain`s ?
Thanks

**Comment by srvrco** [comment]
Hi, 

You are right I should update the documentation to make it clearer. 

using "-r" will just list out those domains that need to be renewed and cannot be used at the same time as "-c" 

"-c" will run the command for those domains that need to be renewed so 

> checkssl -l /etc/letsencrypt/live/ -e 60 -c '/path/renew_ssl.py -r -u '

should do what you want ( note: there is no "-r" in there )

**Comment by srvrco** [comment]
I've updated the code to remove this issue (i.e. to allow both -r and -c to be specified)

**Comment by ZeusF1** [comment]
yeah removed -r fixed issue.

in general it inputs domain after command right?

so -c 'mail mail@box'
and script will add domain after this command right?
can I manage place where it can be added?

**Comment by srvrco** [comment]
correct.   so it would run 
> mail mail@box $domain
if $domain needed renewing in that case. 

Can you give me an example of how else you'd like it to work ? (i.e. the domain placed at some point other than the end ? ).   My instinctive reaction would be to just create a bash script called "renew_domain" or similar, which takes a single argument "domain" and then you can do anything you like with it.

**Comment by ZeusF1** [comment]
@srvrco 
Its ok, just was need to clarify.
