### ISSUE TITLE
Error:  Syntaxfehler beim unerwarteten Wort `newline'

### ISSUE THREAD

**Issue by cmonty14** [srvrco/checkssl#15]
Hi,

when I run checkssl as root (with Debian 8) I get this error:
`root@vm100-revproxy:/usr/local/bin# checkssl
/usr/local/bin/checkssl: Zeile 5: Syntaxfehler beim unerwarteten Wort `newline'
/usr/local/bin/checkssl: Zeile 5: `<!DOCTYPE html>'
`

What's causing this issue?

**Comment by sampod** [comment]
It seems that your 'checkssl'-file is a web page. You probably got the download page instead of the script.

Try downloading the script again with following command:
`curl --silent https://raw.githubusercontent.com/srvrco/checkssl/master/checkssl > checkssl ; chmod 700 checkssl`
