### ISSUE TITLE
grep: Invalid range end

### ISSUE THREAD

**Issue by lordcris** [srvrco/checkssl#2]
The line 
 ISSUER=$(echo "$CERTINFO" | openssl x509 -noout -issuer 2>/dev/null| grep -Eo "/CN=[a-Z' 0-9]*"| cut -c 5-)

gives me an "grep: Invalid range end" on my centos 7 using locale LANG=C

modifying the grep argomen to 

grep -Eo "/CN=[a-zA-Z' 0-9]*"| cut -c 5-)

 fixes the error.

here is a link to a similar issue
https://serverfault.com/questions/464026/running-a-script-containing-find-with-a-regexp-fails-in-cron-but-works-in-a-shel

**Comment by srvrco** [comment]
Thanks - that will teach me to take shortcuts -- I'll update it later today.

**Comment by srvrco** [comment]
updated ( in 2 places).   Thanks

**Comment by lordcris** [comment]
you made a small mistake on line 173

  ISSUER=$(echo "$CERTINFO" | openssl x509 -noout -issuer 2>/dev/null| grep -Eo "/CN=[a-zA_Z' 0-9]*"| cut -c 5-)

should be 
ISSUER=$(echo "$CERTINFO" | openssl x509 -noout -issuer 2>/dev/null| grep -Eo "/CN=[a-zA-Z' 0-9]*"| cut -c 5-)

A_Z  => A-Z

**Comment by srvrco** [comment]
Oops, thanks.  updated amongst adding some other changes
