### ISSUE TITLE
Renewals

### ISSUE THREAD

**Issue by MrSleeps** [srvrco/checkssl#3]
How far do you want to go with this script? I'm pondering about adding the ability to auto-renew the certificates without having to call an external script, if that's something you'll be interested in?

**Comment by srvrco** [comment]
Yes, I'm interested.   At the moment I use this in a cron job which, for certs that need renewals, it uses acme-tiny to renew (via the -c option).  I'd be interested in doing it all in bash though, so yes I'm up for it.

**Comment by srvrco** [comment]
I created this under an alternative script ( which I can potentially merge components later if that's the best option).   it's slightly different than some of the LE scripts in that it enables you to place the challenge files, and certifiicates on a remote server, as well as the local box)  if required ( and you have an SSH key on the remote server. 

Have a look at https://github.com/srvrco/getssl and please provide any feedback there. 

The challenge really is all the different configurations people may have, so I've done it with config files to allow flexibility.
