### ISSUE TITLE
Support for BSD version of date

### ISSUE THREAD

**Issue by dreynolds** [srvrco/checkssl#6]
I'm using this on a Mac which uses the BSD date command rather than the GNU version which has a few differences and as such I get a few errors.

It would be nice if the script could figure out which version to use and work with either.

**Comment by srvrco** [comment]
Can you give me details of the errors ? (or roughly where they are, so I can generate them )

**Comment by dreynolds** [comment]
```
$ bash checkssl davidreynolds.me.uk
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

Domain               cert issued for            valid until               cert issued by                possible issues?
davidreynolds.me.uk  davidreynolds.me.uk (alt)  Nov  8 08:47:00 2016 GMT  Let's Encrypt Authority X3
```

I'm not sure exactly where it's being called. Let me know if you want me to test any further.

**Comment by srvrco** [comment]
Please update to the latest version and test 

The other option is installing / using gdate

**Comment by dreynolds** [comment]
Looks good, although I think you left in some `set +x` by mistake?

Thanks for fixing so quickly though!

**Comment by srvrco** [comment]
opps, thanks - updated version to remove set--x and set+x
