### ISSUE TITLE
Multiple services per domain?

### ISSUE THREAD

**Issue by killerbees19** [srvrco/checkssl#8]
Reference: [Implement multiple remote checks?](https://github.com/srvrco/getssl/issues/148)

Check multiple services (Postfix: SMTPS or SMTP with STARTTLS, Dovecot: IMAPS/POP3S or IMAP/POP3 with STARTTLS, …) for each domain or some of them.

**Comment by srvrco** [comment]
Completed in version 1.08

**Comment by killerbees19** [comment]
Thanks for the quick implementation! :-)

But I think there is a missing `${REMOTE_EXTRA}` after `"${DOMAIN}:${PORT}"`. imaps/pop3s works, but e.g. smtp (with starttls) not.

**Comment by srvrco** [comment]
You are right -  I'll updated it.

**Comment by srvrco** [comment]
Updated.

**Comment by killerbees19** [comment]
btw: You should reset **REMOTE_EXTRA** to an empty string in the loop. Currently it's value is from the previous domain, which results in funny things like that: `openssl s_client -servername ***** -connect *****:443 -starttls smtp`

**Comment by srvrco** [comment]
Thanks, updated.
